#!/bin/bash
#
#       * File     : natmap_callback_notify_push
#       * Author   : sunowsir (rebuild with jshn)
#       * Mail     : sunowsir@163.com
#       * Github   : github.com/sunowsir

WORK_DIR="$(dirname "$(readlink -f "${0}")")"
source "${WORK_DIR}/natmap_callback.config"

sc_send_proc() {
    local text="$1"
    local desp="$2"
    local key="$3"

    local postdata="text=$text&desp=$desp"
    local opts=(
        "--header" "Content-type: application/x-www-form-urlencoded"
        "--data" "$postdata"
    )

    local url="https://sctapi.ftqq.com/${key}.send"
    if [[ "$key" =~ ^sctp([0-9]+)t ]]; then
        local num="${BASH_REMATCH[1]}"
        url="https://${num}.push.ft07.com/send/${key}.send"
    fi

    local result
    result=$(curl -X POST -s -o /dev/null -w "%{http_code}" "$url" "${opts[@]}")
    echo "$result"
}
